<?php

namespace FreeElephants\GeneralPi\Nette;

use FreeElephants\GeneralPi\ClassContainerInterface;
use Nette\PhpGenerator\Helpers;
use Nette\PhpGenerator\PhpNamespace;

/**
 * Generated by free-elephants/general-pi
 */
class ClassContainer implements ClassContainerInterface
{
	/**
	 * @var PhpNamespace
	 */
	private $phpNamespace;
	private $filename;

	public function __construct(PhpNamespace $phpNamespace)
	{
		$this->phpNamespace = $phpNamespace;
	}

	public function stringify(): string
	{
		$content = Helpers::tabsToSpaces($this->phpNamespace->__toString());
		return $content;
	}


	public function __toString(): string
	{
		return $this->stringify();
	}

	public function setClassFilename(string $filename)
	{
		$this->filename = $filename;
	}

	public function getClassFilename(): string
	{
		return $this->filename;
	}
}
