<?php

namespace FreeElephants\GeneralPi\Cli\Command;

use Symfony\Component\Console\Tester\CommandTester;

class CreateAbstractTest extends AbstractCreateCommandTest
{

	public function testExecute()
	{
		$fixtureFilename = self::GENERATED_FIXTURE_PATH . '/Foo/Bar.php';
		$this->assertFileNotExists($fixtureFilename);

		$cmd = $this->createCommand(CreateAbstract::class, 'create:abstract');

		$commandTester = new CommandTester($cmd);
		$commandTester->execute([
			'command' => $cmd->getName(),
			'className' => 'Fixtures\\Generated\\Foo\\Bar',
		]);

		$this->assertFileExists($fixtureFilename);

		$expectedFileContent = <<<PHP
<?php

namespace Fixtures\Generated\Foo;

/**
 * Generated by free-elephants/general-pi
 */
abstract class Bar
{
}

PHP;
		$actualFileContent = file_get_contents($fixtureFilename);
		$this->assertSame($expectedFileContent, $actualFileContent);
	}
}
